services:
  # Backend Service
  - type: web
    name: visnet-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: DATABASE_URL
        fromDatabase:
          name: visnet-db
          property: connectionString
      - key: PORT
        value: 3000

  # Frontend Service
  - type: static
    name: visnet-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist/frontend/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

# Database
databases:
  - name: visnet-db
    plan: free
    databaseName: visnet_elearning
    user: visnet_user
